import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "components/Navbar";
import About from "components/About";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Snigdho Dip Howlader</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Navbar>Snigdho Dip Howlader</Navbar>
      <About />
    </>
  );
};

export default Home;
